# Python 3.11 tabanlı bir görüntü kullanıyoruz
FROM python:3.11

# ODBC sürücüsü ve gerekli araçları yükleyin
RUN apt-get update && \
    apt-get install -y \
    curl \
    gnupg \
    && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/prod.list > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update \
    && ACCEPT_EULA=Y apt-get install -y msodbcsql17

# Diğer bağımlılıkları ve uygulamayı yükleyin
COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt

# Uygulamanızı çalıştırın
CMD ["gunicorn", "app:app"]
