# Temel imaj olarak Python 3.11 kullan
FROM python:3.11

# Gerekli sistem paketlerini yükle
RUN apt-get update && \
    apt-get install -y unixodbc unixodbc-dev \
                       curl gnupg apt-transport-https

# Microsoft SQL Server ODBC sürücüsünü yüklemek için Microsoft'un GPG anahtarını ekleyin
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -

# Microsoft SQL Server ODBC sürücüsünün deposunu ekleyin
RUN echo "deb [arch=amd64] https://packages.microsoft.com/debian/11/prod bullseye main" | tee /etc/apt/sources.list.d/mssql-release.list

# Paket listesini güncelleyin ve ODBC Driver 17'yi yükleyin
RUN apt-get update && \
    ACCEPT_EULA=Y apt-get install -y msodbcsql17

# ODBC Driver 17 için yapılandırma dosyasını oluşturun
RUN echo "[ODBC Driver 17 for SQL Server]" > /etc/odbcinst.ini && \
    echo "Description=Microsoft ODBC Driver 17 for SQL Server" >> /etc/odbcinst.ini && \
    echo "Driver=/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.10.so.1.1" >> /etc/odbcinst.ini

# Çalışma dizinini ayarla
WORKDIR /app

# Gereksinimlerinizi yükleyin
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Uygulama dosyalarınızı kopyalayın
COPY . .

# Uygulamanızı çalıştırmak için gerekli komut
CMD ["gunicorn", "-b", "0.0.0.0:8000", "app:app"]
